name: Sync Repositories

on:
  push:
    branches:
      - master
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Sync changes to destination repository
      env:
        REPO_URL: https://angww:${{ secrets.GH_TOKEN_ANG }}@github.com/tabelaturnot/TabelaTurnot.github.io.git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote add destination $REPO_URL
        git push --force destination +refs/heads/master:refs/heads/master
    - name: Clean and reset working directory
      run: |
        git clean -fdx
        git reset --hard
    - name: Sync repository content
      run: |
        rsync -av --delete --exclude '.git' ./ ../destination-repo/
        cd ../destination-repo/
        rm -rf /.github
        git add .
        git commit -m "Sync from source repository" || echo "No changes to commit"
        git push $REPO_URL main
